pizza_app/config/routes.rb
Rails.application.routes.draw do
 
  devise_for :customers

  get 'pizzas/showpizzalist', to: 'pizzas#showpizzalist'
  resources :pizzas 

  get 'orders/checkout', to: 'orders#checkout'
  resources :orders
  
  resource :customer

  get 'home/splashpage'
  get 'home/menu'

  root 'home#splashpage'

end

pizza_app/app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    self.table_name = 'customer'

    validates :name, presence: true
    validates :phone, presence: true, uniqueness: true
    validates :address, presence: true 

end

pizza_app/app/models/item.rb
class Item < ActiveRecord::Base
    self.table_name = 'item'

    self.inheritance_column = :ruby_type
end

pizza_app/app/models/order.rb
class Order < ActiveRecord::Base
    self.table_name = 'order'


end

pizza_app/app/models/order_item.rb
class OrderItem < ActiveRecord::Base



end

pizza_app/app/models/schema_migration.rb
class SchemaMigration < ActiveRecord::Base



end

pizza_app/app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
  acts_as_shopping_cart
end

pizza_app/app/models/shopping_cart_item.rb
class ShoppingCartItem < ActiveRecord::Base
  acts_as_shopping_cart_item
end

pizza_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_customer!, :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(customer)
    home_menu_path
  end

  def after_sign_out_path_for(customer)
    home_splashpage_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone, :address, :name])
  end

end

pizza_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_customer!, only: [:splashpage]
  
  def splashpage
  	 render
  end

  def menu
  	if !session.has_key?("cart_id") 
  		@cart = ShoppingCart.create
  		session[:cart_id] = @cart.id
  	end
  	render
  end
end

pizza_app/app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def index
		@orders = Order.where(:customer_id => current_customer.id)
	end

	def new
		@cart = ShoppingCart.find(session[:cart_id])
		@cartitems = ShoppingCartItem.where(owner_id: session[:cart_id])
		@item = Item.find(params[:item_id])

		quantity = 1
		for cartitem in @cartitems
			if cartitem.item_id == @item.id
				quantity = cartitem.quantity + 1
				@cart.remove(cartitem, cartitem.quantity)
			end 	
		end
		@cart.add(@item,@item.price, quantity)
		redirect_to pizzas_path
	end

	def create
		@order = Order.create(:customer_id => current_customer.id, :date => DateTime.now)
		@cartitems = ShoppingCartItem.where(owner_id: session[:cart_id])
		totalPrice = 0
		for item in @cartitems
			itemPrice = item.quantity * item.price_cents / 100
			totalPrice += itemPrice
			@order_item =  OrderItem.create(:order_id => @order.id, :item_id => item.id)
		end
		@order.price = totalPrice
		@order.save
		@cart = ShoppingCart.create
  		session[:cart_id] = @cart.id
		render 'thankyou'
	end

	def checkout
		@cartitems = ShoppingCartItem.where(owner_id: session[:cart_id])
		@checkoutitems = []
		@totalPrice = 0.0
		for cartItem in @cartitems
			itemPrice = cartItem.quantity * cartItem.price_cents / 100
			@totalPrice += itemPrice
			checkoutItem = Item.find(cartItem.item_id)
			@checkoutitems.push checkoutItem
		end
	end

end

pizza_app/app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
	def index
		@pizzas = []
		@drinks = []
		@sides = []
		@items = Item.all

		if session.has_key?(:cart_id)
			@cart = ShoppingCart.find(session[:cart_id])
		else
			@cart = ShoppingCart.create
			session[:cart_id] = @cart.id
		end
		for item in @items
			if item.availability == false
				next
			elsif item.type == 'Pizza'
				@pizzas.push item
			elsif item.type == 'Drink'
				@drinks.push item
			else
				@sides.push item
			end
		end
	end

	def show
		if params[:id] == 'showpizzalist' or request.url.include? 'showpizzalist'
			@items = Item.all
			render 'showpizzalist'
		else
			@item = Item.find(params[:id])
			if @item.availability == false
				@makeAvailability = 'true'
				@availabilityText = 'Enable'
			else
				@makeAvailability = 'false'
				@availabilityText = 'Disable'
			end
		end
	end

	def new
		@item = Item.new
	end

	def edit
		@item = Item.find(params[:id])
	end

	def create
		@item = Item.new(item_params)
		@item.save
		redirect_to action: 'show', id: 'showpizzalist'
	end

	def update
		@item = Item.find(params[:id])

		if @item.update(item_params)
			redirect_to action: 'show', id: params[:id]
		else
			render 'edit'
		end
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		@items = Item.all
		render 'showpizzalist'
	end

	def showpizzalist
		@items = Item.all
	end

	

	private 
	def item_params
		params.require(:item).permit(:name, :type, :description, :price, :availability)
	end

	def destroy_multiple
		render plain: params[:item_ids].inspect
	end
end

pizza_app/app/helpers/application_helper.rb
module ApplicationHelper
end

pizza_app/app/helpers/home_helper.rb
module HomeHelper
end

pizza_app/app/helpers/orders_helper.rb
module OrdersHelper
end

pizza_app/app/helpers/pizzas_helper.rb
module PizzasHelper
end

pizza_app/app/views/home/menu.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

	<!-- header -->
	<%= render :partial => "shared/header" %> 

	<!-- main body container -->
	<div class="container">
		<div class="row menu-icons">
			<div class="col-md-4 menu-icon">
				<%= link_to pizzas_path :anchor => "pizzaSection" do %>
				<p><i class="fa fa-pie-chart" aria-hidden="true"></i></p>
				<span class="menu-title">Pizzas</span>
				<% end %>
			</div>
			<div class="col-md-4 menu-icon">
			<%= link_to pizzas_path :anchor => "sidesSection" do %>
				<p><i class="fa fa-cutlery" aria-hidden="true"></i></p>
				<span class="menu-title">Sides</span>
				<% end %>
			</div>
			<div class="col-md-4 menu-icon">
			<%= link_to pizzas_path :anchor => "drinksSection" do %>
				<p><i class="fa fa-glass" aria-hidden="true"></i></p>
				<span class="menu-title">Drinks</span>
				<% end %>
			</div>
		</div>
	</div>

	<!-- footer -->
	<%= render :partial => "shared/footer" %> 
</body>
</html>

pizza_app/app/views/home/splashpage.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Online Pizza Order</title>
</head>
<body>
	
	<%= render :partial => "shared/header" %> 

	<div class="container">

		<div id="myCarousel" class="carousel slide">
			<!-- Indicators -->
			<ol class="carousel-indicators">
				<li data-target="#myCarousel" data-slide-to="0"></li>
				<li data-target="#myCarousel" data-slide-to="1"></li>
				<li data-target="#myCarousel" data-slide-to="2"></li>
			</ol>

			<!-- Wrapper for slides -->
			<div class="carousel-inner" role="listbox">
				<div class="item active">
					<img src="/images/offer1.png" alt="Chania">
				</div>

				<div class="item">
					<img src="/images/offer2.png" alt="Flower">
				</div>

				<div class="item">
					<img src="/images/offer3.png" alt="Flower">
				</div>
			</div>
		</div>

		<!-- Left and right controls -->
		<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
			<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
			<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>

	<%= render :partial => "shared/footer" %>

	
</body>
</html>

pizza_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PizzaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<p class="alert"><%= alert %></p>

</body>
</html>

pizza_app/app/views/orders/checkout.html.erb
<%= render :partial => "shared/header" %> 



<div class="container">
  <div class="row col-md-12">
    <div class="center-block vertical-center jumbotron"> 
      <h2 class="text-center order-review">Review Order</h2>
      <table >
      <tr>
        
        <div><th class="col-xs-2">Name</th></div>
        <div><th class="col-xs-1">Price</th></div>
        <div><th class="col-xs-5">Desciption</th></div>

      </tr>
      <%= div_for(@checkoutitems, :class => "row col-md-8") do |item| %>
        <tr>
        <td><span class="price text-center">
          <span class="pizza-title text-center"><%= item.name %></span>
          </td>
          <td>
          <span>$<%= item.price %>
        </span>
        </td>
        <hr>
        <td>
        <span><%= item.description %></span>
        </td>
        <td>
        <div class="col-md-4">
        <img class="checkoutitem-img center-block" src="/images/sample-pizza.png" alt="sample-pizza">
      </div>
      </td>
      </tr>
      <% end %>
      
      <div class="complete-order center-block">
        <span id="totalPrice" class="text-center">Total price : </span>
        <hr>
        <span> $<%= @totalPrice %></span>
        <hr>
        <%= link_to orders_path, :method => "post" do %>
        <button class="btn text-center center-block btn-default">Place Order</button>
        </tr>
        <% end %>
      </div>
    </div>

  </div>
</div>

pizza_app/app/views/orders/index.html.erb
<%= render :partial => "shared/header" %> 


<div class="container ">
  <div class="row" class="orders-table">
    <h3>Order History</h3>
    <div><%= link_to 'Back', :back %></div>
    <table id="">
      <tr>
        <div><th class="col-xs-1">Order id</th></div>
        <div><th class="col-xs-1">Date</th></div>
        <div ><th class="col-xs-1">Price</th></div>
        <div><th class="col-xs-1">Desciption</th></div>
      </tr>

      <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td>
          <%= ActiveSupport::TimeZone["Central Time (US & Canada)"].parse(order.date.to_s).utc.to_date.strftime(" %b %e, %l:%M %p ")[1..-1]%>
          
        </td>
        <td><%= order.price %></td>
        <td>Not available</td>

      </tr>
      <% end %>

    </table>

  </div>

</div>



<%= render :partial => "shared/footer" %> 

pizza_app/app/views/orders/thankyou.html.erb
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title></title>
  <link href='https://fonts.googleapis.com/css?family=Lato:300,400|Montserrat:700' rel='stylesheet' type='text/css'>
  <style>
    @import url(//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css);
    @import url(//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css);
  </style>
  <link rel="stylesheet" href="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/default_thank_you.css">
  <script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/jquery-1.9.1.min.js"></script>
  <script src="https://2-22-4-dot-lead-pages.appspot.com/static/lp918/min/html5shiv.js"></script>
</head>
<body>

  <%= render :partial => "shared/header" %> 
  <header class="site-header thankyou" id="header">
    <h1 class="site-header__title" data-lead-id="site-header-title">THANK YOU!</h1>
  </header>

  <div class="main-content">
    <i class="fa fa-check main-content__checkmark" id="checkmark"></i>
    <p>Your order id: <%= @order_item.id %> </p>
    <p class="main-content__body" data-lead-id="main-content-body">Thanks a bunch for trying this out. This is a mock pizza store. No order was placed. ;) </p>
  </div>

  <footer class="site-footer" id="footer">
    <p class="site-footer__fineprint" id="fineprint">Copyright ©2016 | All Rights Reserved</p>
  </footer>

<%= render :partial => "shared/footer" %> 

pizza_app/app/views/pizzas/_drinksGallery.html.erb
<div id="drinksSection" class="row drink-items">
	<h1>Drinks</h4>
	<%= div_for(@drinks, :class => "col-md-4 drink") do |item| %>
		<img class="center-block" src="/images/drinks/pepsi_soda_can.png" alt="sample-drink">
		<span class="drink-title text-center"><%= item.name %></span>
		<span class="hidden price"><%= item.price %></span>
		<span class="hidden id"><%= item.id %></span>
		<span class="drink-info text-center"><%= item.description %></span>
		<button class="btn cd-add-to-cart center-block btn-default">Add</button>
	<% end %>
</div>


		
		
		
		
		
		

pizza_app/app/views/pizzas/_pizzaGallery.html.erb
<div id="pizzaSection" class="row pizza-items">
	<h1>Pizzas</h4>
	<%= div_for(@pizzas, :class => "col-md-4 pizza") do |item| %>
		<img class="center-block" src="/images/sample-pizza.png" alt="sample-pizza">
		<span class="pizza-title text-center"><%= item.name %></span>
		<span class="hidden price"><%= item.price %></span>
		<span class="hidden id"><%= item.id %></span>
		<span class="pizza-info text-center"><%= item.description %></span>
		<button class="btn cd-add-to-cart center-block btn-default">Add</button>
				
		
	<% end %>
</div>

pizza_app/app/views/pizzas/_sidesGallery.html.erb
<div id="sidesSection" class="row side-items">
	<h1>Sides</h4>
	<%= div_for(@sides, :class => "col-md-4 side") do |item| %>
		<img class="center-block" src="/images/sides-fries.png" alt="sample-side">
		<span class="side-title text-center"><%= item.name %></span>
		<span class="side-info text-center"><%= item.description %></span>
		<span class="hidden price"><%= item.price %></span>
		<span class="hidden id"><%= item.id %></span>
		<button class="btn cd-add-to-cart center-block btn-default">Add</button>
	<% end %>
</div>


	
	
		
		
		
		
		
		

pizza_app/app/views/pizzas/edit.html.erb
	<div class="container">
		<div class="row">
			
			<div class="col-md-6 center-block">
				<%= form_for :item, url: pizza_path, method: :patch do |f| %>
				<p>
					<%= f.label :name %><br>
					<%= f.text_field :name %>
				</p>

				<p>
					<%= f.label :description %><br>
					<%= f.text_area :description %>
				</p>

				<p>
					<%= f.label :price %><br>
					<%= f.number_field :price, :step => 0.1 %>
				</p>



				<p>
					<%= f.label :type %><br>
					<%= f.select :type, %w[Pizza Side Drink] %>
				</p>

				<p>
					<%= f.submit %>
				</p>
				<% end %>
			</div>
			
		</div>
	</div>

pizza_app/app/views/pizzas/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Online Pizza Order</title>
</head>
<body>

	<!-- header -->
	<%= render :partial => "shared/header" %> 

	<!-- main body container -->
	<div class="container">
		<%= render :partial => "pizzaGallery" %>
		<hr> 
		<%= render :partial => "sidesGallery"%> 
		<hr>
		<%= render :partial => "drinksGallery"%> 
	</div>

	<%= render :partial => "shared/cart" %> 

	<!-- footer -->
	<%= render :partial => "shared/footer" %> 
</body>
</html>

pizza_app/app/views/pizzas/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	Create pizza accessible only to admin.

	<div class="container">
		<div class="row">
			

			<div class="col-md-6 center-block">
				<%= form_for :item, url: pizzas_path do |f| %>
				<p>
					<%= f.label :name %><br>
					<%= f.text_field :name %>
				</p>

				<p>
					<%= f.label :description %><br>
					<%= f.text_area :description %>
				</p>

				<p>
					<%= f.label :price %><br>
					<%= f.number_field :price, :step => 0.1 %>
				</p>



				<p>
					<%= f.label :type %><br>
					<%= f.select :type, %w[Pizza Side Drink] %>
				</p>

				<p>
					<%= f.submit %>
				</p>
				<% end %>
			</div>
		</div>
	</div>
</body>
</html> 

pizza_app/app/views/pizzas/show.html.erb
<p>Id : <%= @item.id %></p>
	<p>Name :  <%= @item.name %></p>
	<p>Price :<%= @item.price %></p>
	<p>Desciption: <%= @item.description %></p>
	<p>Availability: <%= @item.availability %></p>
	<p>
		<%= link_to 'Edit', edit_pizza_path(@item) %> | 
		<%= link_to @availabilityText, pizza_path( :item => {:availability => @makeAvailability}), :method => :put%> |
		<%= link_to 'Delete', pizza_path(@item), :method => :delete %> 
	</p>
	<%= link_to 'Show All Items', pizza_path(:item => {:id => :'showpizzalist'}) %>
</body>
</html>

pizza_app/app/views/pizzas/showpizzalist.html.erb
<%= render :partial => "shared/header" %> 

<div class="container">
	<div class="row orders-table">
		<div class="col-md-3"><h3>Listing Items</h3></div>
		<table >
			<tr>
				<div><th class="col-xs-1">Id</th></div>
				<div><th class="col-xs-2">Name</th></div>
				<div><th class="col-xs-1">Price</th></div>
				<div><th class="col-xs-5">Desciption</th></div>
				<div><th class="col-xs-1">Availability</th></div>
				<div><th class="col-xs-2">Actions</th></div>
			</tr>

			<% @items.each do |item| %>
			<tr>
				<td><%= item.id %></td>
				<td><%= item.name %></td>
				<td><%= item.price %></td>
				<td><%= item.description %></td>
				<td><%= item.availability %></td>

				<td>
					<%= link_to 'Show', pizza_path(item) %> |
					<%= link_to 'Delete', pizza_path(item), :method => "delete" %>
					
				</td>

			</tr>
			<% end %>

		</table>
	</div>

</div>

<%= render :partial => "shared/footer" %> 

pizza_app/app/views/shared/_cart.html.erb
<div class="cd-cart-container empty">
	<a href="#0" class="cd-cart-trigger">
		Cart
		<ul class="count"> <!-- cart items count -->
			<li>0</li>
			<li>0</li>
		</ul> <!-- .count -->
	</a>

	<div class="cd-cart">
		<div class="wrapper">
			<header>
				<h2>Cart</h2>
				<span class="undo">Item removed. <a href="#0">Undo</a></span>
			</header>
			
			<div class="body">
				<ul>
					<!-- products added to the cart will be inserted here using JavaScript -->
				</ul>
			</div>

			<footer>
				<%= link_to orders_checkout_path, :class => "checkout btn" do %>
					<em>Checkout</em>
				<% end %>
			</footer>
		</div>
	</div> <!-- .cd-cart -->
</div> <!-- cd-cart-container -->

pizza_app/app/views/shared/_footer.html.erb
<footer class="footer">
	<div class="container">
		<div class="row first-footer-row">
			<div class="col-md-4">
				<h3 class="footer-top logo--footer" tabindex="0">
					<img src="/images/pizza-brand-logo.jpg" alt="Order best pizza" width="60px">
				</h3>
			</div>
			<div class="col-md-4"></div>
			<div class="col-md-4 social-container">
				<i class="fa fa-facebook-official" aria-hidden="true"></i>
				<i class="fa fa-instagram" aria-hidden="true"></i>

			</div>
		</div>

		<div class="row">
			<div class="col-md-4">
				<ul>
					<li>
						<a href="/home/about">
							About
						</a>
					</li>
					<li>
						<a href="#">
							Careers
						</a>
					</li>
					<li>
						<a href="#">
							Culture
						</a>
					</li>
				</ul>
			</div>
			<div class="col-md-4">
				<ul>
					<li>
						<a href="#">
							Blog
						</a>
					</li>
					<li>
						<a href="#">
							Community
						</a>
					</li>
					<li>
						<a href="#">
							Contact
						</a>
					</li>
				</ul>
			</div>

			<div class="col-md-4">
				<a class="item active selected" href="#" style="padding-left: 28px !important;">English</a>
				<a class="item" href="#" style="padding-left: 28px !important;">Español</a>
				<a class="item" href="#" style="padding-left: 28px !important;">Indonesian</a>
			</div>
		</div>                                                        <div class="clear"></div>
	</div>
	<div class="clear"></div>
</div>
</div>
</div>
</footer>

pizza_app/app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" id="navbar-bootstrapoverrides">
		<div class="container-fluid">
			<div class="navbar-header">
				<%= link_to home_splashpage_path do %>
				<span class="navbar-brand"><img alt="Brand" src="/images/pizza-brand-logo.jpg"></span>
				<span id="shop-title">La Pizzaria</span>
				<% end %>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<div class="nav navbar-nav navbar-right">
					
					<%- if customer_signed_in? and !current_customer.admin? %>
						
							<%= link_to home_menu_path do %>

								<button class="btn btn-default accountMenu" type="button" aria-expanded="true">
								<span class="header-img">
									<i class="fa fa-map-o" aria-hidden="true"></i>
								</span>
									 Menu
								</button>
							<% end %>
						<span class="dropdown">

						  <button class="btn btn-default dropdown-toggle accountMenu" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
						     <span class="header-img">
						     	<i class="fa fa-user-circle" aria-hidden="true"></i>
						     </span>
						     Account
						    <span class="caret"></span>
						  </button>
						  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
						    <li>
						    	<%= link_to 'Orders', orders_path %>
						    </li>
						    <li>
						    	<%= link_to 'Account Details', edit_customer_registration_path%>
						    </li>
						    <li role="separator" class="divider"></li>
						    <li>
						    <li>
						    	<%= link_to 'Sign out', destroy_customer_session_path, :method => :delete%>
						    </li>

						  </ul>
						</span>

					<%elsif customer_signed_in? and current_customer.admin?%>

						<%= link_to pizzas_showpizzalist_path, :class => "accountMenu btn-default btn" do%>
							Admin Section
						<% end %>
						<%= link_to 'Sign out', destroy_customer_session_path, :class =>"accountMenu btn btn-default", :method => :delete%>

					<% else %>
						<%= link_to new_customer_session_path do %>
						<span id="signin">Sign In</span>
						<% end %>
						<%= link_to new_customer_registration_path do %>
						<span id="signup">Sign Up</span>
						<% end %>
					<% end %>

					
				</div>	
			</div>
			
		</div>
	</nav>